version: 2.1
jobs:
  build:
    machine: true
    steps:
      - run: |
          docker build . -t erfangc/sdk-generator:latest
workflows:
  version: 2
  default:
    jobs:
      - build:
          filters:
            branches:
              only: master
        